rm temp ; 
echo START PROG ~/nofib/shootout/n-body/ >> temp; 
echo STARTLOG >> temp ;# echo 1 ; stack exec exp ~/nofib/shootout/n-body/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/shootout/fasta/ >> temp; 
echo STARTLOG >> temp ;# echo 2 ; stack exec exp ~/nofib/shootout/fasta/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/shootout/binary-trees/ >> temp; 
echo STARTLOG >> temp ;# echo 3 ; stack exec exp ~/nofib/shootout/binary-trees/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/shootout/pidigits/ >> temp; 
echo STARTLOG >> temp ;# echo 4 ; stack exec exp ~/nofib/shootout/pidigits/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/shootout/fannkuch-redux/ >> temp; 
echo STARTLOG >> temp ;# echo 5 ; stack exec exp ~/nofib/shootout/fannkuch-redux/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/real/reptile/ >> temp; 
echo STARTLOG >> temp ;echo 8 ; stack exec exp ~/nofib/real/reptile/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/real/fem/ >> temp; 
echo STARTLOG >> temp ;echo 19 ; stack exec exp ~/nofib/real/fem/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/real/hidden/ >> temp; 
echo STARTLOG >> temp ;echo 36 ; stack exec exp ~/nofib/real/hidden/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/real/cacheprof/ >> temp; 
echo STARTLOG >> temp ;echo 50 ; stack exec exp ~/nofib/real/cacheprof/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/real/fulsom/ >> temp; 
echo STARTLOG >> temp ;echo 53 ; stack exec exp ~/nofib/real/fulsom/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/real/maillist/ >> temp; 
echo STARTLOG >> temp ;# echo 66 ; stack exec exp ~/nofib/real/maillist/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/real/prolog/ >> temp; 
echo STARTLOG >> temp ;# echo 68 ; stack exec exp ~/nofib/real/prolog/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/real/pic/ >> temp; 
echo STARTLOG >> temp ;echo 77 ; stack exec exp ~/nofib/real/pic/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/real/anna/ >> temp; 
echo STARTLOG >> temp ;echo 88 ; stack exec exp ~/nofib/real/anna/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/real/fluid/ >> temp; 
echo STARTLOG >> temp ;echo 118 ; stack exec exp ~/nofib/real/fluid/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/real/gg/ >> temp; 
echo STARTLOG >> temp ;echo 135 ; stack exec exp ~/nofib/real/gg/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/real/scs/ >> temp; 
echo STARTLOG >> temp ;echo 144 ; stack exec exp ~/nofib/real/scs/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/real/gamteb/ >> temp; 
echo STARTLOG >> temp ;echo 151 ; stack exec exp ~/nofib/real/gamteb/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/real/rsa/ >> temp; 
echo STARTLOG >> temp ;echo 164 ; stack exec exp ~/nofib/real/rsa/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/real/symalg/ >> temp; 
echo STARTLOG >> temp ;echo 167 ; stack exec exp ~/nofib/real/symalg/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/real/infer/ >> temp; 
echo STARTLOG >> temp ;# echo 179 ; stack exec exp ~/nofib/real/infer/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/scc/ >> temp; 
echo STARTLOG >> temp ;echo 193 ; stack exec exp ~/nofib/spectral/scc/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/minimax/ >> temp; 
echo STARTLOG >> temp ;echo 196 ; stack exec exp ~/nofib/spectral/minimax/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/boyer2/ >> temp; 
echo STARTLOG >> temp ;echo 202 ; stack exec exp ~/nofib/spectral/boyer2/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/integer/ >> temp; 
echo STARTLOG >> temp ;echo 206 ; stack exec exp ~/nofib/spectral/integer/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/cryptarithm1/ >> temp; 
echo STARTLOG >> temp ;echo 207 ; stack exec exp ~/nofib/spectral/cryptarithm1/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/sorting/ >> temp;
echo STARTLOG >> temp ;echo 208 ; stack exec exp ~/nofib/spectral/sorting/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/expert/ >> temp; 
echo STARTLOG >> temp ;echo 212 ; stack exec exp ~/nofib/spectral/expert/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/simple/ >> temp;
echo STARTLOG >> temp ;# echo 216 ; stack exec exp ~/nofib/spectral/simple/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/cichelli/ >> temp; 
echo STARTLOG >> temp ;# echo 217 ; stack exec exp ~/nofib/spectral/cichelli/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/awards/ >> temp; 
echo STARTLOG >> temp ;echo 221 ; stack exec exp ~/nofib/spectral/awards/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/power/ >> temp; 
echo STARTLOG >> temp ;echo 223 ; stack exec exp ~/nofib/spectral/power/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/multiplier/ >> temp; 
echo STARTLOG >> temp ;echo 224 ; stack exec exp ~/nofib/spectral/multiplier/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/puzzle/ >> temp; 
echo STARTLOG >> temp ;# echo 225 ; stack exec exp ~/nofib/spectral/puzzle/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/cse/ >> temp; 
echo STARTLOG >> temp ;# echo 226 ; stack exec exp ~/nofib/spectral/cse/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/eliza/ >> temp; 
echo STARTLOG >> temp ;echo 228 ; stack exec exp ~/nofib/spectral/eliza/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/clausify/ >> temp; 
echo STARTLOG >> temp ;echo 229 ; stack exec exp ~/nofib/spectral/clausify/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/ansi/ >> temp; 
echo STARTLOG >> temp ;# echo 230 ; stack exec exp ~/nofib/spectral/ansi/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/atom/ >> temp;
echo STARTLOG >> temp ;echo 231 ; stack exec exp ~/nofib/spectral/atom/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/lcss/ >> temp; 
echo STARTLOG >> temp ;echo 232 ; stack exec exp ~/nofib/spectral/lcss/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/treejoin/ >> temp; 
echo STARTLOG >> temp ;# echo 233 ; stack exec exp ~/nofib/spectral/treejoin/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/gcd/ >> temp; 
echo STARTLOG >> temp ;echo 234 ; stack exec exp ~/nofib/spectral/gcd/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/calendar/ >> temp; 
echo STARTLOG >> temp ;echo 235 ; stack exec exp ~/nofib/spectral/calendar/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/cryptarithm2/ >> temp; 
echo STARTLOG >> temp ;# echo 236 ; stack exec exp ~/nofib/spectral/cryptarithm2/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/fish/ >> temp; 
echo STARTLOG >> temp ;echo 237 ; stack exec exp ~/nofib/spectral/fish/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/life/ >> temp;
echo STARTLOG >> temp ;echo 238 ; stack exec exp ~/nofib/spectral/life/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/banner/ >> temp; 
echo STARTLOG >> temp ;echo 239 ; stack exec exp ~/nofib/spectral/banner/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/spectral/pretty/ >> temp;
echo STARTLOG >> temp ;echo 240 ; stack exec exp ~/nofib/spectral/pretty/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/imaginary/bernouilli/ >> temp; 
echo STARTLOG >> temp ;echo 243 ; stack exec exp ~/nofib/imaginary/bernouilli/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/imaginary/gen_regexps/ >> temp; 
echo STARTLOG >> temp ;echo 244 ; stack exec exp ~/nofib/imaginary/gen_regexps/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/imaginary/x2n1/ >> temp; 
echo STARTLOG >> temp ;echo 245 ; stack exec exp ~/nofib/imaginary/x2n1/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/imaginary/wheel-sieve2/ >> temp; 
echo STARTLOG >> temp ;echo 246 ; stack exec exp ~/nofib/imaginary/wheel-sieve2/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/imaginary/primes/ >> temp; 
echo STARTLOG >> temp ;echo 247 ; stack exec exp ~/nofib/imaginary/primes/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/imaginary/exp3_8/ >> temp;
echo STARTLOG >> temp ;echo 248 ; stack exec exp ~/nofib/imaginary/exp3_8/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/imaginary/kahan/ >> temp; 
echo STARTLOG >> temp ;# echo 249 ; stack exec exp ~/nofib/imaginary/kahan/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/imaginary/queens/ >> temp; 
echo STARTLOG >> temp ;echo 250 ; stack exec exp ~/nofib/imaginary/queens/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/imaginary/paraffins/ >> temp; 
echo STARTLOG >> temp ;echo 251 ; stack exec exp ~/nofib/imaginary/paraffins/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/imaginary/wheel-sieve1/ >> temp; 
echo STARTLOG >> temp ;echo 252 ; stack exec exp ~/nofib/imaginary/wheel-sieve1/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/imaginary/tak/ >> temp; 
echo STARTLOG >> temp ;echo 253 ; stack exec exp ~/nofib/imaginary/tak/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/imaginary/rfib/ >> temp; 
echo STARTLOG >> temp ;echo 254 ; stack exec exp ~/nofib/imaginary/rfib/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
echo START PROG ~/nofib/imaginary/integrate/ >> temp; 
echo STARTLOG >> temp ;echo 255 ; stack exec exp ~/nofib/imaginary/integrate/Main.hs.opt >> temp ; 
echo ENDLOG >> temp ;
